# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89676f9d2a5eaa549b6cf085b0a9fc4d0f2b8fcb3ed871274a55bdddd88a2801934003d7f8672765bc497802d8b087a4e9fecbd3ee6fe7b1033cdb8b01f27cfc

test:
  secret_key_base: 5d4dfa1cb8dd193bcd55dd42a6e62c47c897c4717eae316f61bf0f044164e600d07fdfeacbc62eeed925f27876959d6fcd036683dd09d78361885b67a8217c5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
